<?php
/**
 * Cached Configuration File
 *
 * This file was generated by WP-Jarvis framework.
 * DO NOT modify this file manually.
 *
 * Generated: 2026-01-19 10:32:47
 *
 * To regenerate, run: wp jarvis configuration:cache
 * To clear, run: wp jarvis cache:clear --configuration
 */

return array (
  'app' =>
  array (
    'prefix' => 'BRA',
    'version' => '1.0.0',
    'slug' => 'bra-calculator',
    'name' => 'BRA Calculator',
    'textdomain' => 'bra-calculator',
    'namespace' => 'BraCalculator\\\\App',
    'rest_namespace' => 'bra-calculator/v1',
    'storage_folder' => 'bra-calculator',
    'env' => 'local',
    'debug' => true,
    'url' => 'http://localhost',
    'locale' => 'en',
    'clean_on_uninstall' => false,
    'providers' =>
    array (
      0 => 'BraCalculator\\App\\Providers\\AppServiceProvider',
      1 => 'BraCalculator\\App\\Providers\\EventServiceProvider',
      2 => 'BraCalculator\\App\\Providers\\NotificationServiceProvider',
      3 => 'BraCalculator\\App\\Providers\\RouteServiceProvider',
    ),
    'aliases' =>
    array (
    ),
    'tinymce_button' => true,
  ),
  'content' =>
  array (
    'auto_discover' => true,
    'post_types' =>
    array (
      'book' =>
      array (
        'label' => 'Books',
        'description' => 'Book collection',
        'public' => true,
        'hierarchical' => false,
        'supports' =>
        array (
          0 => 'title',
          1 => 'editor',
          2 => 'thumbnail',
          3 => 'excerpt',
          4 => 'custom-fields',
        ),
        'rewrite' =>
        array (
          'slug' => 'books',
          'with_front' => true,
        ),
        'taxonomies' =>
        array (
          0 => 'book_category',
          1 => 'book_tag',
        ),
        'menu_icon' => 'dashicons-book-alt',
        'menu_position' => 20,
      ),
    ),
    'taxonomies' =>
    array (
      'book_category' =>
      array (
        'post_types' =>
        array (
          0 => 'book',
        ),
        'label' => 'Book Categories',
        'labels' =>
        array (
          'name' => 'Book Categories',
          'singular_name' => 'Book Category',
          'menu_name' => 'Book Categories',
          'all_items' => 'All Categories',
          'edit_item' => 'Edit Category',
          'update_item' => 'Update Category',
          'add_new_item' => 'Add New Category',
          'new_item_name' => 'New Category Name',
          'parent_item' => 'Parent Category',
          'parent_item_colon' => 'Parent Category:',
          'search_items' => 'Search Categories',
          'popular_items' => 'Popular Categories',
          'separate_items_with_and' => 'and',
          'add_or_remove_items' => 'Add or remove categories',
          'choose_from_most_used' => 'Choose from the most used categories',
          'not_found' => 'No categories found.',
        ),
        'public' => true,
        'hierarchical' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_admin_column' => true,
        'query_var' => true,
        'rewrite' =>
        array (
          'slug' => 'book-categories',
          'with_front' => false,
          'hierarchical' => true,
        ),
        'show_in_rest' => true,
        'show_in_quickedit' => true,
        'show_in_nav_menus' => false,
      ),
      'book_tag' =>
      array (
        'post_types' =>
        array (
          0 => 'book',
        ),
        'label' => 'Book Tags',
        'public' => true,
        'hierarchical' => false,
        'show_ui' => true,
        'show_in_menu' => false,
        'show_in_rest' => true,
        'query_var' => true,
        'rewrite' =>
        array (
          'slug' => 'book-tags',
          'with_front' => false,
        ),
      ),
    ),
    'metaboxes' =>
    array (
      'book_details' =>
      array (
        'title' => 'Book Details',
        'post_types' =>
        array (
          0 => 'book',
        ),
        'context' => 'normal',
        'priority' => 'high',
        'fields' =>
        array (
          'isbn' =>
          array (
            'type' => 'text',
            'label' => 'ISBN',
            'default' => '',
            'required' => true,
          ),
          'author' =>
          array (
            'type' => 'text',
            'label' => 'Author',
            'default' => '',
            'required' => true,
          ),
          'publisher' =>
          array (
            'type' => 'text',
            'label' => 'Publisher',
            'default' => '',
          ),
          'publish_date' =>
          array (
            'type' => 'date',
            'label' => 'Publish Date',
            'default' => '',
          ),
          'price' =>
          array (
            'type' => 'number',
            'label' => 'Price',
            'default' => 0,
            'min' => 0,
            'step' => 0.01,
          ),
          'pages' =>
          array (
            'type' => 'number',
            'label' => 'Pages',
            'default' => 0,
            'min' => 0,
          ),
          'cover_image' =>
          array (
            'type' => 'image_upload',
            'label' => 'Cover Image',
          ),
          'description' =>
          array (
            'type' => 'textarea',
            'label' => 'Description',
            'rows' => 5,
          ),
        ),
      ),
    ),
    'widgets' =>
    array (
      'contact_info' =>
      array (
        'id' => 'contact_info',
        'name' => 'Contact Info',
        'description' => 'Display contact information',
        'fields' =>
        array (
          'title' =>
          array (
            'type' => 'text',
            'label' => 'Widget Title',
            'default' => 'Contact Us',
          ),
          'phone' =>
          array (
            'type' => 'text',
            'label' => 'Phone Number',
            'placeholder' => '+1 (555) 123-4567',
          ),
          'email' =>
          array (
            'type' => 'email',
            'label' => 'Email Address',
            'placeholder' => 'contact@example.com',
          ),
          'address' =>
          array (
            'type' => 'textarea',
            'label' => 'Address',
            'rows' => 3,
          ),
        ),
      ),
    ),
    'shortcodes' =>
    array (
      'alert' =>
      array (
        'tag' => 'alert',
        'allow_content' => true,
        'attributes' =>
        array (
          'type' =>
          array (
            'type' => 'text',
            'default' => 'info',
          ),
          'title' =>
          array (
            'type' => 'text',
            'default' => '',
          ),
          'content' =>
          array (
            'type' => 'textarea',
            'default' => '',
            'rows' => 3,
          ),
        ),
      ),
      'button' =>
      array (
        'tag' => 'button',
        'attributes' =>
        array (
          'label' =>
          array (
            'type' => 'text',
            'default' => 'Click Me',
          ),
          'link' =>
          array (
            'type' => 'url',
            'default' => '#',
          ),
          'size' =>
          array (
            'type' => 'select',
            'default' => 'medium',
            'choices' =>
            array (
              'small' => 'Small',
              'medium' => 'Medium',
              'large' => 'Large',
            ),
          ),
          'color' =>
          array (
            'type' => 'select',
            'default' => 'primary',
            'choices' =>
            array (
              'primary' => 'Primary',
              'secondary' => 'Secondary',
              'success' => 'Success',
              'danger' => 'Danger',
            ),
          ),
          'block' =>
          array (
            'type' => 'checkbox',
            'default' => false,
          ),
        ),
      ),
    ),
    'settings_pages' =>
    array (
      'general_settings' =>
      array (
        'page_title' => 'General Settings',
        'menu_title' => 'General',
        'capability' => 'manage_options',
        'icon_url' => 'dashicons-admin-generic',
        'sections' =>
        array (
          'site_info' =>
          array (
            'title' => 'Site Information',
            'description' => 'Configure basic site details',
            'fields' =>
            array (
              'site_name' =>
              array (
                'type' => 'text',
                'label' => 'Site Name',
                'default' => 'Plugin Development',
              ),
              'site_tagline' =>
              array (
                'type' => 'text',
                'label' => 'Site Tagline',
                'default' => '',
              ),
              'site_url' =>
              array (
                'type' => 'url',
                'label' => 'Site URL',
                'default' => 'http://wp-jarvis.test',
              ),
            ),
          ),
          'contact' =>
          array (
            'title' => 'Contact Information',
            'description' => 'Contact details',
            'fields' =>
            array (
              'contact_email' =>
              array (
                'type' => 'email',
                'label' => 'Contact Email',
                'default' => 'qaisarali789@gmail.com',
              ),
              'contact_phone' =>
              array (
                'type' => 'text',
                'label' => 'Contact Phone',
                'placeholder' => '+1 (555) 123-4567',
              ),
            ),
          ),
        ),
      ),
    ),
    'blocks' =>
    array (
      'testimonial' =>
      array (
        'name' => 'testimonial',
        'title' => 'Testimonial',
        'description' => 'Display customer testimonials',
        'category' => 'widgets',
        'icon' => 'format-quote',
        'keywords' =>
        array (
          0 => 'quote',
          1 => 'review',
          2 => 'feedback',
        ),
        'attributes' =>
        array (
          'author' =>
          array (
            'type' => 'text',
            'default' => '',
          ),
          'role' =>
          array (
            'type' => 'text',
            'default' => '',
          ),
          'content' =>
          array (
            'type' => 'textarea',
            'default' => '',
            'rows' => 3,
          ),
        ),
        'supports' =>
        array (
          'align' => true,
          'color' =>
          array (
            'text' => true,
            'background' => true,
          ),
        ),
      ),
      'cta_button' =>
      array (
        'name' => 'cta_button',
        'title' => 'Call to Action Button',
        'description' => 'Add a call to action button',
        'category' => 'common',
        'icon' => 'button',
        'attributes' =>
        array (
          'label' =>
          array (
            'type' => 'text',
            'default' => 'Learn More',
          ),
          'link' =>
          array (
            'type' => 'url',
            'default' => '#',
          ),
          'style' =>
          array (
            'type' => 'select',
            'default' => 'primary',
            'choices' =>
            array (
              'primary' => 'Primary',
              'secondary' => 'Secondary',
              'outline' => 'Outline',
              'text' => 'Text Only',
            ),
          ),
          'size' =>
          array (
            'type' => 'select',
            'default' => 'medium',
            'choices' =>
            array (
              'small' => 'Small',
              'medium' => 'Medium',
              'large' => 'Large',
            ),
          ),
          'block' =>
          array (
            'type' => 'checkbox',
            'default' => false,
          ),
        ),
        'supports' =>
        array (
          'align' => true,
          'color' =>
          array (
            'text' => true,
            'background' => true,
          ),
        ),
      ),
    ),
  ),
  'database' =>
  array (
    'default' => 'wordpress',
    'connections' =>
    array (
      'wordpress' =>
      array (
        'driver' => 'mysql',
        'host' => 'localhost',
        'port' => '3306',
        'database' => 'wp-jarvis',
        'username' => 'root',
        'password' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => 'wp_',
        'prefix_indexes' => true,
        'strict' => false,
        'engine' => NULL,
      ),
      'mysql' =>
      array (
        'driver' => 'mysql',
        'host' => '127.0.0.1',
        'port' => '3306',
        'database' => 'forge',
        'username' => 'forge',
        'password' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'prefix_indexes' => true,
        'strict' => true,
        'engine' => NULL,
      ),
      'sqlite' =>
      array (
        'driver' => 'sqlite',
        'database' => 'D:\\laragon\\www\\wp-jarvis\\wp-content\\plugins\\bra-calculator\\storage\\database.sqlite',
        'prefix' => '',
      ),
    ),
    'migrations' => 'bra_calculator_migrations',
  ),
  'index' => 1,
  'requirements' =>
  array (
    'min_php_version' => '8.1',
    'min_wp_version' => '6.0',
    'is_multisite_compatible' => true,
    'php_extensions' =>
    array (
      0 => 'json',
      1 => 'mbstring',
    ),
    'required_plugins' =>
    array (
    ),
  ),
);
