<?php
/**
 * Cached Routes File
 *
 * This file was generated by WP-Jarvis framework.
 * DO NOT modify this file manually.
 *
 * Generated: 2026-01-19 10:23:54
 *
 * To regenerate, run: wp jarvis routes:cache
 * To clear, run: wp jarvis cache:clear --routes
 */

return array (
  'files' =>
  array (
    0 => 'D:\\laragon\\www\\wp-jarvis\\wp-content\\plugins\\bra-calculator\\routes\\api.php',
    1 => 'D:\\laragon\\www\\wp-jarvis\\wp-content\\plugins\\bra-calculator\\routes\\admin.php',
    2 => 'D:\\laragon\\www\\wp-jarvis\\wp-content\\plugins\\bra-calculator\\routes\\web.php',
  ),
  'timestamp' => 1768818234,
);
